#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------
JAVAC         = javac
JAR           = jar
JAVACFLAGS    = $(GENFLAGS)
CLASSEXT      = .class
CLASSDIR      = classes/
OUTPUT_OPTION = -d $(CLASSDIR)
COMPILE.java  = $(JAVAC) $(JAVACFLAGS) -cp $(JAVACCPATH) 
JAVACCPATH    = "$(CLASSDIR):dcpssaj.jar:"
MAKEFILE      = Makefile.saj_casinoroyale_types
DEPENDENCIES  = $(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
GENFLAGS      =  
CLASSES       =  $(CLASSDIR)CR/*$(CLASSEXT)
JARCLASSES    =  CR/*$(CLASSEXT)
JAREXT        = .jar
JARFILE       = $(LTARGETDIR)$(LIBPREFIX)saj_casinoroyale_types$(LIBSUFFIX)$(JAREXT)
MANIFEST      = saj_casinoroyale_types.manifest
JARFLAGS      = cvfm
SRC           = CR/*.java

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(JARFILE)

$(JARFILE): $(CLASSES) $(CLASSDIR)$(MANIFEST)
	@$(TESTDIRSTART) "$(LTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(LTARGETDIR)"
	cd $(CLASSDIR) && $(JAR) $(JARFLAGS) $(JARFILE) $(MANIFEST) $(JARCLASSES) 
	$(MV) $(CLASSDIR)/$(JARFILE) .

$(CLASSDIR)$(MANIFEST):
	echo Class-Path: dcpssaj.jar > $(CLASSDIR)$(MANIFEST)

GENERATED_DIRTY = CR

CR: ../idl/cr.idl
	$(OSPL_HOME)/bin/idlpp -I $(OSPL_HOME)/etc/idl -l java ../idl/cr.idl

.PRECIOUS: $(GENERATED_DIRTY)
$(CLASSES): $(GENERATED_DIRTY)

generated: $(GENERATED_DIRTY)
	@-:

$(CLASSDIR)CR/*$(CLASSEXT): CR
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) CR/*.java

clean:
	-$(RM) $(CLASSES)

realclean: clean
	-$(RM) $(SHLIB) $(JARFILE)
	-$(RM) $(GENERATED_DIRTY)
	-$(RM) $(CLASSDIR)$(MANIFEST)

check-syntax:
	$(COMPILE.java) $(EXPORTFLAGS) $(CHK_SOURCES)

