#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------
JAVAC         = javac
JAR           = jar
JAVACFLAGS    = $(GENFLAGS) -sourcepath ../src
CLASSEXT      = .class
CLASSDIR      = classes/
OUTPUT_OPTION = -d $(CLASSDIR)
COMPILE.java  = $(JAVAC) $(JAVACFLAGS) -cp $(JAVACCPATH) 
JAVACCPATH    = "saj_casinoroyale_types.jar:$(CLASSDIR):dcpssaj.jar:junit-4.12.jar:hamcrest-core-1.3.jar:”
MAKEFILE      = Makefile.saj_casinoroyale_junit
DEPENDENCIES  = $(MAKEFILE)
LTARGETDIR    = ./
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
TESTDIRSTART  = test -d
TESTDIREND    = ||
TOUCH         = touch
GENFLAGS      =  
CLASSES       =  $(CLASSDIR)UnitTestMain$(CLASSEXT)
JARCLASSES    =  UnitTestMain$(CLASSEXT)
JAREXT        = .jar
MAINCLASS     = UnitTestMain
JARFILE       = $(LTARGETDIR)$(LIBPREFIX)saj_casinoroyale_junit$(LIBSUFFIX)$(JAREXT)
MANIFEST      = saj_casinoroyale_junit.manifest
JARFLAGS      = cvfm
SRC           = ../src/UnitTestMain.java

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(JARFILE)

$(JARFILE): $(CLASSES) $(CLASSDIR)$(MANIFEST)
	@$(TESTDIRSTART) "$(LTARGETDIR)" $(TESTDIREND) $(MKDIR) "$(LTARGETDIR)"
	cd $(CLASSDIR) && $(JAR) $(JARFLAGS) $(JARFILE) $(MANIFEST) $(JARCLASSES) 
	$(MV) $(CLASSDIR)/$(JARFILE) .

$(CLASSDIR)$(MANIFEST):
	echo Class-Path: saj_casinoroyale_types.jar dcpssaj.jar junit-4.12.jar hamcrest-core-1.3.jar > $(CLASSDIR)$(MANIFEST)
	echo Main-Class: $(MAINCLASS) >> $(CLASSDIR)$(MANIFEST)

generated: $(GENERATED_DIRTY)
	@-:

$(CLASSDIR)UnitTestMain$(CLASSEXT): ../src/UnitTestMain.java
	@$(TESTDIRSTART) "$(CLASSDIR)" $(TESTDIREND) $(MKDIR) "$(CLASSDIR)"
	$(COMPILE.java) $(EXPORTFLAGS) $(OUTPUT_OPTION) ../src/UnitTestMain.java

clean:
	-$(RM) $(CLASSES)

realclean: clean
	-$(RM) $(BIN)
	-$(RM) $(CLASSDIR)$(MANIFEST)

check-syntax:
	$(COMPILE.java) $(EXPORTFLAGS) $(CHK_SOURCES)

